### ISSUE TITLE
Enter not moving state when time has completed

### ISSUE THREAD

**Issue by lunad-bsquare** [ColorCookie-dev/porsmo#10]
When the timer has completed and is counting excess, there's a bit of additional text saying `[Enter]: Next`, however pressing enter doesn't actually do anything. Before the time ends enter will forward instantly.

I believe [this](https://github.com/ColorCookie-dev/porsmo/blob/3a72ada2108482145dcbd016d664d7ee57364430/src/porsmo/pomodoro.rs#L107) line is the bug, where a `>=` instead of a `<` should be used, but I'm not 100% sure on it as it would change behaviour pre-timer-completion.

**Comment by ColorCookie-dev** [comment]
That does seem to be the case, I will check and confirm, and will fix it later. Anyway thanks for the issue.

**Comment by ColorCookie-dev** [comment]
bb44cf7e1aa17dabeb7f2fbca124dcaebe7e6635 fixes this problem, and pre-timer-completion with Enter is not a bug, it is you wish to skip it, you need to use skip mechanics
