### ISSUE TITLE
Failing test in `format.rs`

### ISSUE THREAD

**Issue by GrizzlT** [ColorCookie-dev/porsmo#11]
When running the tests for this project, the compiler throws an error about mismatching `Duration` with `an integer`.
See here:
https://github.com/ColorCookie-dev/porsmo/blob/4a629d69bc9993433a595f9396f6e16fa7c010d6/src/porsmo/format.rs#L80

**Comment by ColorCookie-dev** [comment]
Probably, the test wasn't updated. However, I had plans to change the parse_time function, thus didn't bother to update it. Which is now updated, I deleted the test completely. I don't think I want to create more test for this.

**Comment by GrizzlT** [comment]
Awesome, thanks for the quick response!
