### ISSUE TITLE
Cursor stuttering in Windows terminal

### ISSUE THREAD

**Issue by kavita-p** [ColorCookie-dev/porsmo#12]
Cursor stutters significantly in Windows Terminal. This appears to be specific to the terminal emulator; I didn't see the same effect in a native Powershell window. Demo [here](https://www.youtube.com/watch?v=Y99V6T15BMs).

**Comment by ColorCookie-dev** [comment]
Terminal Emulator? Are you talking about the new terminal app from microsoft? And BTW the demo video is private.

**Comment by kavita-p** [comment]
I am talking about the terminal app from Microsoft, which I may be incorrectly calling an emulator. Also sorry about making the video private; it was meant to be unlisted, which hopefully it is now.

**Comment by ColorCookie-dev** [comment]
I think hiding the cursor will be sufficient, never liked it being shown in porsmo.

**Comment by ColorCookie-dev** [comment]
Tell me if the cursor is still shown in windows terminal. I can't check because I don't use windows myself.

**Comment by kavita-p** [comment]
Works great, and honestly I like the hidden cursor even on my Unix machines too. Thanks!
