### ISSUE TITLE
Flickering in Windows Terminal

### ISSUE THREAD

**Issue by LatjoLajbin** [ColorCookie-dev/porsmo#13]
Porsmo's rendering is flickering regardless of state and timer mode.

Running in 
Porsmo 0.3.1
Windows Terminal Preview 1.20.10572.0
Windows 10.0.19045

Atlas textrendering engine (no configuration of rendering settings seem to make a difference.

Built with cargo install.
Building from source and running debug target causes the same issue.

![porsmo_issue](https://github.com/ColorCookie-dev/porsmo/assets/7878254/64d3628c-3a4b-4579-9603-011c01c04e24)
Flicker occurs at a fairly stable rate at about twice the frequency of what the gif shows.

Any ideas if I might be doing something wrong?

**Comment by ColorCookie-dev** [comment]
Will be trying to reduce flicker in subsequent commits

**Comment by ColorCookie-dev** [comment]
I accidentally marked it as fixed with a commit, though the flickering should be less now, can you confirm, if it does?

**Comment by LatjoLajbin** [comment]
Apologies for the delayed response.
It looks fantastic now, thank you!
